name: CI - Protobuf & Build

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  proto-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Ensure protoc installed
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Generate protobuf TS
        run: pnpm proto:generate

      - name: Lint & Build
        run: pnpm build

